" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Drew Neil
" Notes:  Based on the 'Blackboard' theme from TextMate.

let colors_name="board"

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#FFFFFF ctermfg=231 guibg=#0B1022 ctermbg=233
